### ISSUE TITLE
#1_Navigation bar

### ISSUE THREAD

**Issue by Auto-Yahwin** [Abiyah1/Edoug#1]
If you are working on this, please do so on a branch other than the main branch. Create a new branch and title it with something corresponding to this issue

**Comment by Abiyah1** [comment]
Thank you for solving the nav bar issue

**Comment by Auto-Yahwin** [comment]
I still need to add the company's logo to the top left. Also, we need to agree on a the color combinations

**Comment by Abiyah1** [comment]
Yes, am still gonna send the logo.I love the background color but I don't like it being a drop-down option.
Also, I made a big mistake and I don't know if you noticed it. I have merged your nav bar branch to the main branch. Let me know how that affects

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 8, 2023 at 12:59 am, ***@***.***> wrote:   


I still need to add the company's logo to the top left. Also, we need to agree on the color combinations
